"""add upload session model

Revision ID: 059d34051d5f
Revises: d917b45fb69f
Create Date: 2026-07-03 06:57:08.094026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '059d34051d5f'
down_revision: Union[str, Sequence[str], None] = 'd917b45fb69f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploadsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sqlmodel.String(), nullable=False),
    sa.Column('object_key', sqlmodel.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.String(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('uploaded_chunks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploadsession_upload_id'), 'uploadsession', ['upload_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploadsession_upload_id'), table_name='uploadsession')
    op.drop_table('uploadsession')
    # ### end Alembic commands ###
