"""add object_key to chunk

Revision ID: 07774c1c45b6
Revises: 3bb30d82f442
Create Date: 2026-07-05 06:54:50.925522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '07774c1c45b6'
down_revision: Union[str, Sequence[str], None] = '3bb30d82f442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk', sa.Column('chunk_number', sa.Integer(), nullable=False))
    op.add_column('chunk', sa.Column('object_key', sqlmodel.String(), nullable=False))
    op.drop_column('chunk', 'chunck_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk', sa.Column('chunck_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('chunk', 'object_key')
    op.drop_column('chunk', 'chunk_number')
    # ### end Alembic commands ###
