"""chunk model

Revision ID: 3bb30d82f442
Revises: 059d34051d5f
Create Date: 2026-07-04 05:46:57.600142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3bb30d82f442'
down_revision: Union[str, Sequence[str], None] = '059d34051d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UploadSession_id', sa.Integer(), nullable=False),
    sa.Column('chunck_number', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('checksum', sqlmodel.String(), nullable=True),
    sa.Column('status', sqlmodel.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['UploadSession_id'], ['uploadsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunk')
    # ### end Alembic commands ###
