"""add dile metadata model

Revision ID: d917b45fb69f
Revises: d1c8a4024df6
Create Date: 2026-07-01 14:48:40.161195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd917b45fb69f'
down_revision: Union[str, Sequence[str], None] = 'd1c8a4024df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('object_key', sqlmodel.String(), nullable=False))
    op.add_column('file', sa.Column('content_type', sqlmodel.String(), nullable=False))
    op.add_column('file', sa.Column('status', sqlmodel.String(), nullable=False))
    op.create_index(op.f('ix_file_object_key'), 'file', ['object_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_object_key'), table_name='file')
    op.drop_column('file', 'status')
    op.drop_column('file', 'content_type')
    op.drop_column('file', 'object_key')
    # ### end Alembic commands ###
